<div style="width:100%; background-color:#181818; color:#f1f1f1; padding:30px 0; text-align:center; border-radius:10px;">

  <img src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExcXVodWNsM3Bia3duZGljZzRqMTI2MGFiZjlkZzBwcmhuaWxydjlpaiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/AOSwwqVjNZlDO/giphy.gif" alt="Beam Oscillation" width="400" style="border-radius:10px;">

  <h3 style="color:#ffffff; margin-top:15px;"><b>Basic Examples of Coding with Jupyter and Python</b></h3>

  <p><b>Author:</b> <a href="http://caceli.net/" style="color:#3ea6ff; text-decoration:none;">Msc. Ing. Carlos Andrés Celi Sánchez</a></p>
  <p><b>Course:</b> Matrix Analisys</p>
  <p><b>Year:</b> MARCH - 2026</p>

</div>

#### Introduction


This notebook presents a very first approach to Python coding using Jupyter Notebook as an educational environment.  
The objective is to help students become familiar with simple commands, variable definition, array manipulation, loops, and basic output visualization.

Although the examples are intentionally simple, they represent the foundation for more advanced applications that will later be used in structural engineering, numerical methods, and matrix-based analysis.

#### Importing Libraries

The first step in many Python workflows is importing the required libraries.  
In this notebook, we start with **NumPy**, which is one of the most important libraries for scientific computing.

NumPy allows us to:
- perform numerical operations efficiently,
- define vectors and matrices,
- create arrays automatically, and
- prepare the basis for future structural and mathematical applications.


In [29]:
import sys
import os
sys.path.append(os.path.abspath(".."))

In [30]:
import numpy as np
import sympy as sp
import pandas as pd

#### Simple Console Messages

Python allows us to print messages in the output area in order to follow the execution of a script.  
This is very useful when we want to organize a numerical routine step by step and identify whether the process is running correctly.

In the following example, colored text and emojis are used only as a visual aid to make the output more intuitive and easier to read.

In [31]:
print("\033[1;36m📌 Step 1: Creating model\033[0m")
print("\033[1;32m✅ Step 2: Analysis completed\033[0m")
print("\033[1;33m⚠️ Step 3: Review results carefully\033[0m")
print("\033[1;31m❌ Step 4: Convergence not achieved\033[0m")

📌 Step 1: Creating model
✅ Step 2: Analysis completed
⚠️ Step 3: Review results carefully
❌ Step 4: Convergence not achieved


#### Basic Variables and Data Types

A Python script is built from variables that store different kinds of information.  
These variables may represent numerical values, text, vectors, matrices, or more complex data structures.

In the next example, we define:
- a numerical result,
- a text variable, and
- an array of values.

This helps illustrate how Python can handle different types of information within the same notebook.

#### Basic Use of Loops

Loops are essential in programming because they allow us to repeat instructions automatically.  
Instead of writing the same command several times, we can use a loop to construct vectors, fill arrays, or process data step by step.

The following examples show two simple approaches:
- filling a NumPy array,
- and building a Python list progressively.

#### Manual and Automatic Matrix Construction

Matrices can be created manually by directly specifying their entries, or automatically by using loops and numerical functions.  
Both approaches are useful in engineering and scientific programming.

The manual definition is convenient for small examples and for checking results by hand, while the automatic construction becomes much more efficient when dealing with larger systems or repetitive patterns.

In [32]:
from repo_maxtrix_analisys import *

In [33]:
a  =  np.sum(2+3)
print("a = ",a)
b  = 'hi'
print('b = ', b)
c = np.array([1,2,3,4])
print('c is', c.astype, 'which value is =', c)

#--- Basic loop for array construction
cc = np.zeros(4)
for i in np.arange(1, 4, 1):
    cc[i] = i+1
cc[0] = 1

#--- Basic loop for array construction
dd = []
for j in np.arange(1,4+1,1):
    dd.append(j)

print('cc = ', cc, ', dd = ', dd)

manu = np.array([[1,5,9,13],[2,6,10,14],[3,7,11,15],[4,8,12,16]])

#--- Basic loop for array construction "Matrix"
auto = np.zeros([4,4])
i = 0
for j in np.arange(1,4+1,1):
    auto[i,:] = np.linspace(j,j+12,4)
    i = i+1

print('\033[1;32m Manual Matrix Array : \033[0m\n', manu)
print('\033[1;36m Automatic Matrix Array : \033[0m\n', auto)

a =  5
b =  hi
c is <built-in method astype of numpy.ndarray object at 0x000001A663269590> which value is = [1 2 3 4]
cc =  [1. 2. 3. 4.] , dd =  [1, 2, 3, 4]
 Manual Matrix Array : 
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
 Automatic Matrix Array : 
 [[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [34]:
def matriz(hola):
    auto = np.zeros([4,4])
    i = 0
    for j in np.arange(1,4+1,1):
        auto[i,:] = np.linspace((j * hola),(j * hola) +12,4)
        i = i+1
   
    return auto

In [35]:
resul = matriz(100)
print('\033[1;36m Automatic Matrix Array : \033[0m\n', resul)
pepito = matriz(1)
print('\033[1;36m Automatic Matrix Array : \033[0m\n', pepito)

 Automatic Matrix Array : 
 [[100. 104. 108. 112.]
 [200. 204. 208. 212.]
 [300. 304. 308. 312.]
 [400. 404. 408. 412.]]
 Automatic Matrix Array : 
 [[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [36]:
h = []
for hola in np.arange(1, 3, 1):
    h.append(matriz(hola))

z = np.vstack(h)

In [37]:
print('\033[1;36m Automatic Matrix Array : \033[0m\n', z)

 Automatic Matrix Array : 
 [[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]
 [ 2.  6. 10. 14.]
 [ 4.  8. 12. 16.]
 [ 6. 10. 14. 18.]
 [ 8. 12. 16. 20.]]


* Use of Class

In [38]:
ejemplo1 = SimpleMatrixStack(3)
auto = ejemplo1.matriz()
auto

array([[ 3.,  7., 11., 15.],
       [ 6., 10., 14., 18.],
       [ 9., 13., 17., 21.],
       [12., 16., 20., 24.]])

#### Inverse matrix calculation

In [39]:
EI = sp.Symbol('EI')
AE = sp.Symbol('AE')
GA = sp.Symbol('GA')
f = sp.Symbol('f')
L = sp.Symbol('L')


F = sp.Matrix([[L/EI, L**2 / (2*EI), 0],
              [L**2 / (2*EI), L**3 / (3*EI) + L*f / (GA), 0],
              [0, 0, L/AE]])

K = F**-1
K

Matrix([
[(12*EI**2*f + 4*EI*GA*L**2)/(12*EI*L*f + GA*L**3),   -6*EI*GA/(12*EI*f + GA*L**2),    0],
[                     -6*EI*GA/(12*EI*f + GA*L**2), 12*EI*GA/(12*EI*L*f + GA*L**3),    0],
[                                                0,                              0, AE/L]])

#### Stiffness Matrix in Local Coordinates (RMF)
![alt text](image.png)
![alt text](image-1.png)

In [40]:
A = 0.3*0.3
I = 0.3**4/12
E = 2000000
G = 15000
L = 5
f = 6/5


In [41]:
def stiffness_matrix_Element_RMF_L(A,I,E,L,G,f):
    Be = 6*E*I*f / (G*A*L**2)
    r = A*E /L
    kp = 2*E*I/L * (2 + Be)/(1 + 2*Be)
    ap = 2*E*I/L * (1 - Be)/(1 - 2*Be)
    bp = 6*E*I/(L**2) * (1)/(1 + 2*Be)
    tp = 12*E*I/(L**3) * (1)/(1 + 2*Be)

    kl = np.array([[r,0,0,-r,0,0],
                [0,tp,bp,0,-tp,bp],
                [0,bp,kp,0,-bp,ap],
                [-r,0,0,r,0,0],
                [0,-tp,-bp,0,tp,-bp],
                [0,bp,ap,0,-bp,kp]], dtype=float)
    
    return kl

In [44]:
pepito = stiffness_matrix_Element_RMF_L(2*A,I,E,L/2,G,f)
pepito_df = pd.DataFrame(pepito)
pepito_df

,0,1,2,3,4,5
0,144000.0,0.000000,0.000000,-144000.0,0.000000,0.000000
1,0.0,481.784387,602.230483,0.0,-481.784387,602.230483
2,0.0,602.230483,1292.788104,0.0,-602.230483,-3012.631579
3,-144000.0,0.000000,0.000000,144000.0,0.000000,0.000000
4,0.0,-481.784387,-602.230483,0.0,481.784387,-602.230483
5,0.0,602.230483,-3012.631579,0.0,-602.230483,1292.788104
